spring.application.name=fitness-tracker
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/fitness_tracker?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate 會自動根據 MySQL 版本選 dialect，不需要手動指定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
# 關閉 Open Session In View（避免效能警告）
spring.jpa.open-in-view=false
